// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aojlkgcxkqzkxohotjwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvamxrZ2N4a3F6a3hvaG90andyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyOTg2NTIsImV4cCI6MjA4ODg3NDY1Mn0.c9lp6XLvJGiYClo3mTLVdA5vmUwHq4ktJ9bUgT2nBFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});